{{ if .Values.ingress.enabled }}
{{- $host := .Values.ingress.host -}}
{{- $serviceName := .Values.service.name -}}
{{- $servicePort := .Values.service.port -}}
{{- $canarySuffix := .Values.canary.suffix -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{ if .Values.canary.enabled }}
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-canary"
    {{ end }}
  name: {{ .Values.service.name }}{{ $canarySuffix }}
spec:
  rules:
    {{- range .Values.ingress.paths }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}{{ $canarySuffix }}
                port:
                  number: {{ $servicePort }}
    {{- end }}
{{ end }}
