{{ if .Values.rbac.enabled  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["kubernetes-client.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  resourceNames: ["externalsecrets.kubernetes-client.io"]
  verbs: ["get", "update"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "watch", "list", "edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
subjects:
- kind: Group
  name: oneapp-internal/oidc/{{ .Values.environment.name  }}/eks-clusters/oneapp/rbac/teams/{{ .Values.team.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin{{ .Values.canary.suffix }}
{{ end }}
---
{{ if .Values.rbacProd.enabled  }} #For prod-ref and prod
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete" ]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["ingress"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list" ]
- apiGroups: [""]
  resources: ["externalsecrets"]
  verbs: ["get", "watch", "list" ]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "edit" ]
- apiGroups: [""]
  resources: ["customresourcedefinitions"]
  resourceNames: ["externalsecrets.kubernetes-client.io"]
  verbs: ["get"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "watch", "list", "edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
subjects:
- kind: Group
  name: oneapp-internal/oidc/{{ .Values.environment.name  }}/eks-clusters/oneapp/rbac/teams/{{ .Values.team.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin{{ .Values.canary.suffix }}
{{ end }}
