{{- if .Values.secretstore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.service.name }}-sa{{ .Values.canary.suffix }}
      region: eu-central-1
      service: SecretsManager
{{- end }}
