apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}{{ .Values.canary.suffix }}
  labels:
    app: {{ .Values.service.name }}{{ .Values.canary.suffix }}
    version: {{ .Values.image.tag }}
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}{{ .Values.canary.suffix }}
