{{ if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-sa{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN }}
{{ end }}
