{{- if .Values.secretstore.enabled }}
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: oneapp-test-secret{{ .Values.canary.suffix }}
  labels:
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  data:
    - secretKey: password
      remoteRef:
        key: oneapp-test-secret
        property: password
{{- end }}
